#!/bin/sh
# script to manage wssd

[ -n "$CTDB_BASE" ] || \
    CTDB_BASE=$(d=$(dirname "$0") ; cd -P "$d" ; dirname "$PWD")

. "${CTDB_BASE}/functions"

load_script_options

service_start ()
{
    service wsdd start
}

service_stop ()
{
    service wsdd stop
}

case "$1" in
startup)
    service_start
    ;;

shutdown)
    service_stop
    ;;

ipreallocated)
    service_stop
    service_start
    ;;

esac

exit 0
